'use client';

import { useState } from 'react';
import { ArrowLeft, CalendarDays, CheckCircle2, Clock3, CreditCard, Gamepad2, Search } from 'lucide-react';

function time(value:string){return new Date(value).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit',hour12:true});}
function dateLabel(value:string){return new Date(value).toLocaleDateString('en-IN',{day:'2-digit',month:'long',year:'numeric'});}
function duration(minutes:number){const h=Math.floor(minutes/60),m=minutes%60;return h?`${h} hr${h>1?'s':''}${m?` ${m} min`:''}`:`${m} min`;}
function payment(value:string){return value==='FULLY_PAID'?'FULLY PAID':value==='ADVANCE_PAID'?'ADVANCE PAID':value==='REFUNDED'?'REFUNDED':'PAYMENT PENDING';}

export default function BookingLookup(){
 const [bookingNo,setBookingNo]=useState(''); const [phone,setPhone]=useState(''); const [result,setResult]=useState<any>(null); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
 async function lookup(){setLoading(true);setError('');setResult(null);try{const p=new URLSearchParams();if(bookingNo.trim())p.set('bookingNo',bookingNo.trim());else p.set('phone',phone.replace(/\s+/g,''));const r=await fetch(`/api/booking-lookup?${p}`);const d=await r.json();if(!r.ok)throw new Error(d.error||'Booking not found.');setResult(d);}catch(e){setError(e instanceof Error?e.message:'Booking not found.');}finally{setLoading(false);}}
 return <main className="min-h-screen px-5 py-10"><div className="mx-auto max-w-3xl"><a href="/" className="inline-flex items-center gap-2 text-sm font-black text-ice"><ArrowLeft className="h-4 w-4"/> BACK TO ARENA</a><div className="mt-8 glass rounded-3xl p-6 sm:p-9"><div className="text-center"><Gamepad2 className="mx-auto h-10 w-10 text-ice"/><p className="mt-4 text-xs font-black tracking-[.3em] text-ice">VS // BOOKING LOOKUP</p><h1 className="mt-3 text-4xl font-black">CHECK MY BOOKING</h1><p className="mt-3 text-sm text-slate-500">Use your booking ID or registered phone number.</p></div><div className="mt-8 grid gap-4 sm:grid-cols-2"><label><span className="mb-2 block text-xs font-black text-slate-500">BOOKING ID</span><input className="w-full rounded-xl border border-white/10 bg-[#081019] p-3" placeholder="VS-12345678" value={bookingNo} onChange={e=>setBookingNo(e.target.value)}/></label><label><span className="mb-2 block text-xs font-black text-slate-500">OR PHONE</span><input className="w-full rounded-xl border border-white/10 bg-[#081019] p-3" placeholder="10-digit mobile number" value={phone} onChange={e=>setPhone(e.target.value)}/></label></div><button className="btn btn-primary mt-5 w-full" disabled={loading||(!bookingNo.trim()&&!phone.trim())} onClick={lookup}><Search className="mr-2 h-4 w-4"/>{loading?'SEARCHING...':'CHECK BOOKING'}</button>{error&&<p className="mt-4 rounded-xl border border-red-400/20 bg-red-400/5 p-4 text-sm font-bold text-red-300">{error}</p>}{result&&<div className="neon mt-7 rounded-2xl p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-black text-slate-500">BOOKING ID</p><p className="mt-1 text-2xl font-black text-ice">{result.bookingNo}</p></div><span className="rounded-full bg-emerald-400/10 px-3 py-2 text-xs font-black text-emerald-300">{result.status}</span></div><div className="mt-6 grid gap-3 sm:grid-cols-2"><Info icon={<CalendarDays/>} label="DATE" value={dateLabel(result.startAt)}/><Info icon={<Clock3/>} label="SESSION" value={`${time(result.startAt)} – ${time(result.endAt)}`}/><Info icon={<Gamepad2/>} label="STATION" value={`${result.station.code} · ${result.station.name}`}/><Info icon={<CreditCard/>} label="PAYMENT" value={payment(result.paymentStatus)}/></div><div className="mt-5 grid grid-cols-3 gap-3"><Money label="TOTAL" value={result.total}/><Money label="PAID" value={result.paidAmount}/><Money label="BALANCE" value={result.balance}/></div><p className="mt-5 text-center text-xs font-bold text-slate-600">Duration: {duration(result.durationMinutes)} · Advance required: ₹{result.advanceAmount}</p></div>}</div></div></main>;
}
function Info({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="rounded-xl border border-white/5 bg-white/[.02] p-4"><div className="flex items-center gap-2 text-ice">{icon}<span className="text-[10px] font-black tracking-widest text-slate-600">{label}</span></div><p className="mt-2 text-sm font-black">{value}</p></div>}
function Money({label,value}:{label:string;value:number}){return <div className="rounded-xl border border-white/5 bg-white/[.02] p-4 text-center"><p className="text-[10px] font-black tracking-widest text-slate-600">{label}</p><p className="mt-2 text-xl font-black">₹{value}</p></div>}
