'use client';

import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { CalendarDays, CheckCircle2, Clock3, LogOut, RefreshCw, XCircle, IndianRupee, CreditCard, Search, Download, CalendarClock, Users, Gamepad2, Activity, CircleDollarSign } from 'lucide-react';
import { useRouter } from 'next/navigation';

type Booking={id:string;bookingNo:string;startAt:string;endAt:string;durationMinutes:number;total:number;advanceAmount:number;paidAmount:number;status:string;paymentStatus:string;station:{code:string;name:string};customer:{name:string;phone:string}};
type Summary={date:string;metrics:{bookings:number;sales:number;collected:number;outstanding:number;advancePending:number;completed:number;playing:number;customers:number};stations:{code:string;name:string;rate:number;bookings:number;revenue:number;playing:boolean}[];upcoming:{id:string;bookingNo:string;customer:string;station:string;startAt:string;endAt:string;status:string;total:number;paidAmount:number}[];hourly:{hour:number;label:string;count:number}[]};
const stations=['ALL','VS-01','VS-02','VS-03']; const statuses=['ALL','PENDING','CONFIRMED','COMPLETED','CANCELLED','NO_SHOW']; const payments=['ALL','PENDING','ADVANCE_PAID','FULLY_PAID','REFUNDED'];
function today(){return new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'});} function time(v:string){return new Date(v).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit',hour12:true,timeZone:'Asia/Kolkata'});} function dateLabel(v:string){return new Date(`${v}T12:00:00`).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'});} function dur(m:number){const h=Math.floor(m/60),r=m%60;return h?`${h} hr${h>1?'s':''}${r?` ${r} min`:''}`:`${r} min`;} function pay(v:string){return v==='ADVANCE_PAID'?'ADVANCE PAID':v==='FULLY_PAID'?'FULLY PAID':v==='REFUNDED'?'REFUNDED':'PAYMENT PENDING';}

export default function AdminDashboard(){
 const router=useRouter(); const [date,setDate]=useState(today()); const [station,setStation]=useState('ALL'); const [status,setStatus]=useState('ALL'); const [paymentStatus,setPaymentStatus]=useState('ALL'); const [q,setQ]=useState(''); const [bookings,setBookings]=useState<Booking[]>([]); const [summary,setSummary]=useState<Summary|null>(null); const [loading,setLoading]=useState(true); const [message,setMessage]=useState(''); const [updating,setUpdating]=useState('');
 async function load(){setLoading(true);setMessage('');try{const p=new URLSearchParams({date});if(station!=='ALL')p.set('station',station);if(status!=='ALL')p.set('status',status);if(paymentStatus!=='ALL')p.set('paymentStatus',paymentStatus);if(q.trim())p.set('q',q.trim());const [r,s]=await Promise.all([fetch(`/api/admin/bookings?${p}`,{cache:'no-store'}),fetch(`/api/admin/summary?date=${date}`,{cache:'no-store'})]);if(r.status===401||s.status===401){router.replace('/admin/login');return;}const d=await r.json();const sd=await s.json();setBookings(Array.isArray(d)?d:[]);setSummary(sd); }catch{setMessage('Could not load the dashboard.')}finally{setLoading(false);}}
 useEffect(()=>{load();},[date,station,status,paymentStatus]);
 const revenue=useMemo(()=>bookings.filter(b=>!['CANCELLED','NO_SHOW'].includes(b.status)).reduce((s,b)=>s+b.paidAmount,0),[bookings]); const sales=useMemo(()=>bookings.filter(b=>!['CANCELLED','NO_SHOW'].includes(b.status)).reduce((s,b)=>s+b.total,0),[bookings]); const pending=useMemo(()=>bookings.filter(b=>b.paymentStatus==='PENDING'&&!['CANCELLED','NO_SHOW'].includes(b.status)).reduce((s,b)=>s+b.advanceAmount,0),[bookings]); const maxHour=Math.max(1,...(summary?.hourly.map(x=>x.count)||[1]));
 async function update(id:string,payload:any){setUpdating(id);setMessage('');const r=await fetch('/api/admin/bookings',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,...payload})});if(r.ok)await load();else{const d=await r.json().catch(()=>({}));setMessage(d.error||'Update failed.');}setUpdating('');}
 async function reschedule(b:Booking){const newDate=window.prompt('New date (YYYY-MM-DD)',new Date(b.startAt).toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'}));if(!newDate)return;const newTime=window.prompt('New start time (HH:MM, 24-hour)',new Date(b.startAt).toLocaleTimeString('en-GB',{timeZone:'Asia/Kolkata',hour:'2-digit',minute:'2-digit'}));if(!newTime)return;const newStation=window.prompt('Station (VS-01 / VS-02 / VS-03)',b.station.code);if(!newStation)return;await update(b.id,{reschedule:{date:newDate,time:newTime,stationCode:newStation,durationMinutes:b.durationMinutes}});}
 async function logout(){await fetch('/api/admin/logout',{method:'POST'});router.replace('/admin/login');router.refresh();}
 function exportCsv(){const rows=[['Booking ID','Customer','Phone','Station','Date','Start','End','Duration','Status','Payment','Total','Paid','Balance'],...bookings.map(b=>[b.bookingNo,b.customer.name,b.customer.phone,b.station.code,new Date(b.startAt).toLocaleDateString('en-IN'),time(b.startAt),time(b.endAt),dur(b.durationMinutes),b.status,pay(b.paymentStatus),b.total,b.paidAmount,Math.max(0,b.total-b.paidAmount)])];const csv=rows.map(r=>r.map(x=>`"${String(x).replaceAll('"','""')}"`).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`vs-gaming-arena-${date}.csv`;a.click();URL.revokeObjectURL(a.href);}
 return <main className="min-h-screen px-4 py-6 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl">
 <header className="mb-6 flex flex-col gap-4 rounded-2xl border border-white/5 bg-[#050a10]/90 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-black tracking-[.25em] text-ice">VS // COMMAND CENTER</p><h1 className="mt-2 text-3xl font-black">ADMIN DASHBOARD</h1><p className="mt-1 text-sm text-slate-500">Live operations · payments · schedule · revenue</p></div><div className="flex flex-wrap gap-2"><button className="btn btn-ghost" onClick={load}><RefreshCw className="mr-2 h-4 w-4"/>Refresh</button><button className="btn btn-ghost" onClick={exportCsv}><Download className="mr-2 h-4 w-4"/>Export CSV</button><button className="btn btn-ghost" onClick={logout}><LogOut className="mr-2 h-4 w-4"/>Logout</button></div></header>
 <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-8"><Metric icon={<CalendarDays/>} label="Bookings" value={String(summary?.metrics.bookings??bookings.length)}/><Metric icon={<CircleDollarSign/>} label="Sales" value={`₹${summary?.metrics.sales??sales}`}/><Metric icon={<IndianRupee/>} label="Collected" value={`₹${summary?.metrics.collected??revenue}`}/><Metric icon={<CreditCard/>} label="Outstanding" value={`₹${summary?.metrics.outstanding??Math.max(sales-revenue,0)}`}/><Metric icon={<CreditCard/>} label="Advance Pending" value={`₹${summary?.metrics.advancePending??pending}`}/><Metric icon={<CheckCircle2/>} label="Completed" value={String(summary?.metrics.completed??0)}/><Metric icon={<Activity/>} label="Playing Now" value={String(summary?.metrics.playing??0)}/><Metric icon={<Users/>} label="Customers" value={String(summary?.metrics.customers??0)}/></section>
 <section className="mt-6 grid gap-4 lg:grid-cols-3"><div className="glass rounded-2xl p-5 lg:col-span-2"><div className="flex items-center justify-between"><div><p className="text-xs font-black tracking-widest text-ice">LIVE STATIONS</p><h2 className="mt-1 text-xl font-black">Arena status</h2></div><span className="rounded-full bg-emerald-400/10 px-3 py-1 text-[10px] font-black text-emerald-300">LIVE</span></div><div className="mt-5 grid gap-3 sm:grid-cols-3">{(summary?.stations||[]).map(s=><div key={s.code} className="rounded-2xl border border-white/5 bg-[#080e15] p-4"><div className="flex items-center justify-between"><span className="text-sm font-black">{s.code}</span><span className={`h-2.5 w-2.5 rounded-full ${s.playing?'bg-red-400':'bg-emerald-400'}`}/></div><p className="mt-3 text-xs font-bold text-slate-400">{s.playing?'PLAYING NOW':'AVAILABLE'}</p><p className="mt-2 text-xs text-slate-600">{s.name}</p><p className="mt-3 text-xs font-bold text-slate-500">{s.bookings} bookings · ₹{s.revenue}</p></div>)}</div></div><div className="glass rounded-2xl p-5"><p className="text-xs font-black tracking-widest text-ice">UPCOMING</p><h2 className="mt-1 text-xl font-black">Next sessions</h2><div className="mt-4 space-y-3">{summary?.upcoming.length?summary.upcoming.slice(0,5).map(b=><div key={b.id} className="flex items-center justify-between rounded-xl border border-white/5 bg-[#080e15] p-3"><div><p className="text-xs font-black">{b.station} · {time(b.startAt)}</p><p className="mt-1 text-xs text-slate-500">{b.customer}</p></div><span className="text-xs font-black text-slate-400">₹{b.total-b.paidAmount} due</span></div>):<p className="py-8 text-center text-sm text-slate-600">No upcoming sessions</p>}</div></div></section>
 <section className="mt-4 grid gap-4 lg:grid-cols-2"><div className="glass rounded-2xl p-5"><p className="text-xs font-black tracking-widest text-ice">PEAK HOURS</p><h2 className="mt-1 text-xl font-black">Bookings by hour</h2><div className="mt-5 flex h-44 items-end gap-2">{(summary?.hourly||[]).map(h=><div key={h.hour} className="flex min-w-0 flex-1 flex-col items-center justify-end gap-2"><span className="text-[9px] font-black text-slate-500">{h.count||''}</span><div className="w-full rounded-t-md bg-cyan-300/60" style={{height:`${Math.max(4,(h.count/maxHour)*120)}px`}}/><span className="text-[8px] font-bold text-slate-600">{h.label.replace(':00','')}</span></div>)}</div></div><div className="glass rounded-2xl p-5"><p className="text-xs font-black tracking-widest text-ice">STATION PERFORMANCE</p><h2 className="mt-1 text-xl font-black">Sales by station</h2><div className="mt-5 space-y-4">{(summary?.stations||[]).map(s=><div key={s.code}><div className="mb-2 flex justify-between text-xs font-black"><span>{s.code} · {s.name}</span><span>₹{s.revenue}</span></div><div className="h-2 overflow-hidden rounded-full bg-white/5"><div className="h-full rounded-full bg-cyan-300" style={{width:`${Math.max(4,(s.revenue/Math.max(1,...(summary?.stations||[]).map(x=>x.revenue)))*100)}%`}}/></div><p className="mt-1 text-[10px] text-slate-600">{s.bookings} booking(s)</p></div>)}</div></div></section>
 <section className="mt-6 rounded-2xl border border-white/5 bg-[#050a10]/90 p-4"><div className="grid gap-3 md:grid-cols-5"><Filter label="DATE"><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></Filter><Filter label="STATION"><select value={station} onChange={e=>setStation(e.target.value)}>{stations.map(x=><option key={x}>{x}</option>)}</select></Filter><Filter label="BOOKING STATUS"><select value={status} onChange={e=>setStatus(e.target.value)}>{statuses.map(x=><option key={x}>{x}</option>)}</select></Filter><Filter label="PAYMENT"><select value={paymentStatus} onChange={e=>setPaymentStatus(e.target.value)}>{payments.map(x=><option key={x}>{x}</option>)}</select></Filter><Filter label="SEARCH"><div className="flex gap-2"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder="ID / name / phone"/><button className="btn btn-primary !p-3" onClick={load}><Search className="h-4 w-4"/></button></div></Filter></div></section>
 {message&&<p className="mt-4 rounded-xl border border-red-400/20 bg-red-400/5 p-3 text-sm font-bold text-red-300">{message}</p>}
 <section className="mt-7 overflow-hidden rounded-2xl border border-white/5 bg-[#050a10]/90"><div className="flex items-center justify-between border-b border-white/5 p-5"><div><p className="text-xs font-black tracking-widest text-ice">SCHEDULE</p><h2 className="mt-1 text-xl font-black">{dateLabel(date)}</h2></div><span className="text-xs font-bold text-slate-600">{loading?'SYNCING...':`${bookings.length} booking(s)`}</span></div>{loading?<div className="p-10 text-center text-sm font-bold text-slate-600">Loading bookings...</div>:bookings.length===0?<div className="p-12 text-center"><Clock3 className="mx-auto h-8 w-8 text-slate-700"/><p className="mt-3 font-black text-slate-500">No bookings found</p></div>:<div className="divide-y divide-white/5">{bookings.map(b=><BookingRow key={b.id} booking={b} onUpdate={update} onReschedule={reschedule} updating={updating===b.id}/>)}</div>}</section>
 <footer className="py-8 text-center text-xs font-bold text-slate-700">VS GAMING ARENA · PUSAD · ADMIN MODE</footer></div></main>;
}
function Metric({icon,label,value}:{icon:ReactNode;label:string;value:string}){return <div className="glass rounded-2xl p-4"><span className="text-ice">{icon}</span><p className="mt-3 text-xl font-black">{value}</p><p className="mt-1 text-[9px] font-black uppercase tracking-wider text-slate-500">{label}</p></div>}
function Filter({label,children}:{label:string;children:ReactNode}){return <label><span className="mb-2 block text-[10px] font-black tracking-widest text-slate-600">{label}</span><div className="[&_input]:w-full [&_input]:rounded-xl [&_input]:border [&_input]:border-white/10 [&_input]:bg-[#0a1016] [&_input]:p-3 [&_input]:text-sm [&_input]:text-white [&_select]:w-full [&_select]:rounded-xl [&_select]:border [&_select]:border-white/10 [&_select]:bg-[#0a1016] [&_select]:p-3 [&_select]:text-sm [&_select]:text-white">{children}</div></label>}
function BookingRow({booking,onUpdate,onReschedule,updating}:{booking:Booking;onUpdate:(id:string,payload:any)=>void;onReschedule:(b:Booking)=>void;updating:boolean}){const unpaid=booking.paymentStatus==='PENDING'&&!['CANCELLED','NO_SHOW'].includes(booking.status);return <article className="p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="rounded-md bg-cyan-300/10 px-2 py-1 text-[10px] font-black text-ice">{booking.bookingNo}</span><span className="rounded-md border border-white/10 px-2 py-1 text-[10px] font-black text-slate-500">{booking.station.code}</span><span className="rounded-md border border-white/10 px-2 py-1 text-[10px] font-black text-slate-500">{booking.status}</span><span className={`rounded-md px-2 py-1 text-[10px] font-black ${unpaid?'bg-yellow-400/10 text-yellow-300':'bg-emerald-400/10 text-emerald-300'}`}>{pay(booking.paymentStatus)}</span></div><h3 className="mt-3 text-lg font-black">{booking.customer.name}</h3><p className="mt-1 text-sm text-slate-500">{booking.customer.phone} · {booking.station.name}</p><p className="mt-2 text-sm font-bold text-slate-300">{time(booking.startAt)} – {time(booking.endAt)} · {dur(booking.durationMinutes)} · Total ₹{booking.total} · Paid ₹{booking.paidAmount} · Balance ₹{Math.max(booking.total-booking.paidAmount,0)}</p>{unpaid&&<p className="mt-2 text-sm font-black text-yellow-300">Advance required: ₹{booking.advanceAmount}</p>}</div><div className="flex flex-wrap gap-2">{unpaid&&<button disabled={updating} className="btn btn-primary text-xs" onClick={()=>onUpdate(booking.id,{paymentStatus:'ADVANCE_PAID'})}>{updating?'Updating...':'Mark Advance Paid'}</button>}{booking.paymentStatus==='ADVANCE_PAID'&&booking.status==='CONFIRMED'&&<button disabled={updating} className="btn btn-ghost text-xs" onClick={()=>onUpdate(booking.id,{paymentStatus:'FULLY_PAID'})}>Mark Fully Paid</button>}{booking.status==='CONFIRMED'&&<button disabled={updating} className="btn btn-ghost text-xs" onClick={()=>onUpdate(booking.id,{status:'COMPLETED'})}><CheckCircle2 className="mr-1 h-4 w-4"/>Complete</button>}{booking.status!=='CANCELLED'&&booking.status!=='COMPLETED'&&booking.status!=='NO_SHOW'&&<button disabled={updating} className="btn btn-ghost text-xs" onClick={()=>onUpdate(booking.id,{status:'CANCELLED'})}><XCircle className="mr-1 h-4 w-4"/>Cancel</button>}{booking.status!=='CANCELLED'&&booking.status!=='COMPLETED'&&<button disabled={updating} className="btn btn-ghost text-xs" onClick={()=>onReschedule(booking)}><CalendarClock className="mr-1 h-4 w-4"/>Reschedule</button>}</div></div></article>}
